### ISSUE TITLE
Idk what is this

### ISSUE THREAD

**Issue by VerweliuS** [Awakened-Redstone/fabric-gen#4]
### Version information

1.1.3

### Reproduction Steps

This problem just appeared out of nowhere

### Crash Report file

============= Ignore the JavaFX warning. =============
���. 23, 2022 3:33:14 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @48ca18e4'
Fabrigen cache loaded
Fabrigen configurations loaded
Getting Yarn version...
Getting license...
Fabrigen configurations loaded
Fabrigen cache loaded
Updating template
Generating mod...
Generating build.gradle
Generating gradle.properties
Generating gradle-wrapper.properties
Generating map-disabler.mixins.json
Generating MapDisabler.java
Generating icon.png
Generating fabric.mod.json
Failed to generate mod!
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 6 column 120 path $.description
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:99)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:68)
	at com.google.gson.JsonParser.parseString(JsonParser.java:50)
	at com.awakenedredstone.fabrigen.FXMLController.generateJavaMod(FXMLController.java:585)
	at com.awakenedredstone.fabrigen.FXMLController.generateTemplate(FXMLController.java:190)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 6 column 120 path $.description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1607)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:501)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:424)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:752)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:698)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 6 more

**Comment by VerweliuS** [comment]
Just removed "s from description

**Comment by Awakened-Redstone** [comment]
I'll work on fixing the issue on the next release, apparently it isn't being escaped when put on the field
Thanks for the report
